** Calling: z3 -nw -in -smt2
[GOOD] ; Automatically generated by SBV. Do not edit.
[GOOD] (set-option :print-success true)
[GOOD] (set-option :global-declarations true)
[GOOD] (set-option :smtlib2_compliant true)
[GOOD] (set-option :diagnostic-output-channel "stdout")
[GOOD] (set-option :produce-models true)
[GOOD] (set-logic ALL) ; external query, using all logics.
[GOOD] ; --- uninterpreted sorts ---
[GOOD] ; --- tuples ---
[GOOD] ; --- sums ---
[GOOD] ; --- literal constants ---
[GOOD] ; --- top level inputs ---
[GOOD] (declare-fun s0 () Bool) ; tracks user variable "x"
[GOOD] ; --- constant tables ---
[GOOD] ; --- non-constant tables ---
[GOOD] ; --- arrays ---
[GOOD] ; --- uninterpreted constants ---
[GOOD] ; --- user defined functions ---
[GOOD] ; --- assignments ---
[GOOD] ; --- arrayDelayeds ---
[GOOD] ; --- arraySetups ---
[GOOD] ; --- delayedEqualities ---
[GOOD] ; --- formula ---
*** Solver   : Z3
*** Exit code: ExitSuccess
CAUGHT EXCEPTION

Data.SBV: Mismatched contexts detected.
***
*** Current context: SBVContext (-7749304166575005736)
*** Mixed with     : SBVContext (-531973508589804280)
***
*** This happens if you call a proof-function (prove/sat/runSMT/isSatisfiable) etc.
*** while another one is in execution, or use results from one such call in another.
*** Please avoid such nested calls, all interactions should be from the same context.
*** See https://github.com/LeventErkok/sbv/issues/71 for several examples.

CallStack (from HasCallStack):
  error, called at ./Data/SBV/Core/Symbolic.hs:1937:48 in sbv-10.9-inplace:Data.SBV.Core.Symbolic